version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    environment:
      BACKEND_USER_ID: 3434
      BACKEND_DEBUG: off
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_DB: vash
      DATABASE_USER: user
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and up images
          command: BACKEND_VERSION=${CIRCLE_SHA1} docker-compose --project-directory . -f backend/compose/common.yml -f backend/compose/production.yml -f database/compose.yml -f webserver/compose.yml up --build --detach
      - run:
          name: Run backend migrations
          command: docker exec -it project_backend_1 python manage.py migrate
      - run:
          name: Run backend tests
          command: docker exec -it project_backend_1 coverage run --source=. -m pytest --emoji
      - run:
          name: Prepare coverage file
          command: |
              docker cp project_backend_1:/code/.coverage . &&
              cp -rp .coverage .coverage-hack &&
              coverage combine --rcfile=backend/code/.coveragerc .coverage .coverage-hack
      - run:
          name: Report coverage
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh)

workflows:
  main:
    jobs:
      - build-and-test
