version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    environment:
      BACKEND_USER_ID: 3434
      BACKEND_DEBUG: off
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_DB: vash
      DATABASE_USER: user
    executor: python/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build images
          command: BACKEND_VERSION=${CIRCLE_SHA1} docker-compose --project-directory . -f backend/compose/common.yml -f backend/compose/production.yml -f database/compose.yml -f webserver/compose.yml build
      - run:
          name: Up images
          command: BACKEND_VERSION=${CIRCLE_SHA1} docker-compose --project-directory . -f backend/compose/common.yml -f backend/compose/production.yml -f database/compose.yml -f webserver/compose.yml up --detach
      - run:
          name: Run backend migrations
          command: docker run backend:${CIRCLE_SHA1} python manage.py migrate
      - run:
          name: Run backend tests and report coverage
          command: >
            CI_ENV=`bash <(curl -s https://codecov.io/env)` &&
            docker run ${CI_ENV} backend:${CIRCLE_SHA1} sh -c "pytest --emoji --cov=. --no-cov-on-fail --cov-report=term:skip-covered && bash <(curl -s https://codecov.io/bash)"

workflows:
  main:
    jobs:
      - build-and-test
