version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    executor: python/default
    environment:
      BACKEND_USER_ID: 3434
      BACKEND_DEBUG: off
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_DB: vash
      DATABASE_USER: user
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and up images
          command: BACKEND_VERSION=${CIRCLE_SHA1} docker-compose --project-directory . -f backend/compose/common.yml -f backend/compose/production.yml -f database/compose.yml -f webserver/compose.yml up --build --detach
      - run:
          name: Run backend migrations
          command: docker exec -it project_backend_1 python manage.py migrate
      - run:
          name: Run backend tests
          command: docker exec -it project_backend_1 pytest --emoji --cov=. --no-cov-on-fail --cov-report=term:skip-covered
      - run:
          name: Copy test coverage from container
          command: docker cp project_backend_1:/code/.coverage .
      # - codecov/upload:
      #     file: .coverage
      #     conf: backend/codecov.yml
      - run:
          name: Report test coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build-and-test
