version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    environment:
      BACKEND_IMAGE: ${CIRCLE_SHA1}
    executor: python/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
        name: Get user id
        command: id -u

workflows:
  main:
    jobs:
      - build-and-test
