version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    environment:
      BACKEND_IMAGE: ${CIRCLE_SHA1}
    executor: python/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
        name: Write user id to shell environment
        command: "export USER_ID=$(id -u) >> $BASH_ENV"
      - run:
        name: Build images
        command: docker-compose --project-directory . -f backend/compose/common.yml -f backend/compose/production.yml -f database/compose.yml -f webserver/compose.yml build

workflows:
  main:
    jobs:
      - build-and-test
